### ISSUE TITLE
Graphical issue with substitutes at end of half

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/GameController#100]
When ending first half, if robot `k` from team `A` is substitute and robot `k`from team `B` had received a penalty, at start of second half,  robot `k` from team `B` is yellow blinking with text (0:00).

Procedure to reproduce the bug:
- Substitute robot 4 from team A
- Penalize robot 4 from team B
- Click on robot 4 of team B to start serving penalty
- Click on second finish + second half
- Robot 4 of team B is now blinking

**Comment by sheepsy90** [comment]
I can have a look on that if it doesn't require a real connected robot.

**Comment by medrimonia** [comment]
Thank you very much, it can perfectly be done without connecting a robot. I did not precise it because I mentioned it was a graphical bug, but the packets sent have the expected behavior: i.e. robot 4 from B has the penalty corresponding to substitute.

**Comment by sheepsy90** [comment]
@medrimonia I fixed the bug - it is in     public void changeSide() in the advanced data - the problem was that the "is serving penalty array was not switched when switching sides" - it might be that other fields are also not switched accordingly like timouts taken and such.

This needs more in depth checking/and/or a unittest to verify switching sides affects all parts of the team data.

The main issue is that the data structure is quite fragmented and there is not simply a Team container that holds all information about a team, but scattered boolean variables arrays for different things.

**Comment by medrimonia** [comment]
Tested and approved.
