### ISSUE TITLE
GamestateVisualizer - fix logos and background image

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#40]
Currently the images for the teams and background is hard coded taken from the SPL folder. This should be done dynamically or you should be able to configure it when opening the Gamestate Visualizer

**Comment by fthielke** [comment]
This is fixed with the newest commit (https://github.com/bhuman/GameController/commit/39fe52c547ca4665bd1535183fafc13a752b453e) in the original GameController repository.

Sorry that this was not done in the first place; when integrating the GameStateVisualizer into the TeamCommunicationMonitor, I forgot about the Humanoid leagues using it as well.

**Comment by sheepsy90** [comment]
@fthielke Can I simply take over the changes you did in the bhuman repo?

**Comment by sheepsy90** [comment]
@fthielke I just took over the changes from  src/teamcomm/TeamCommunicationMonitor.java
