### ISSUE TITLE
Free Kick needs to allow the possibility to take a time-out

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#64]
A free-kick counts as a stoppage of game, so teams should have the possibility to take a time-out. Please make sure that a referee can always call a timeout in any situations. Teams should be able to call a timeout in case of free-kick, goal, or drop ball.

**Comment by sheepsy90** [comment]
This is not possible in the given time. The problem is that we call the timeout sub-state out of being already in a sub-state (Calling Timeout out of Free Kick). Because the sub states are not stackable and the game goes back into ready after a timeout and not just really really freezes during the timeout this involves already 4 states (Global game state - Playing and Read and the two sub states FreeKick and Timeout).

This leads to the following options to solve this:
1. allow timeouts being taken in freekicks but loose the information of the freekick when the game resumes so the game would continue with normal ready and the kickoff for the party that didn't take the timeout

2. Not going back to the state initial in the begin of the timeout and not to ready in the end of the timeout but really freeze the game in the moment the free kick would be occuring and the timeout is taken. 

The long term solution would be to isolate the game clock into it's own object to interact with and thereby not having to juggle 4 different long and other variables that count times during specific states.

**Comment by robocup-hl-tc** [comment]
Free Kicks are not a stoppage of game, so they don't need to allow for a timeout.
