### ISSUE TITLE
SubMode understanding

### ISSUE THREAD

**Issue by StefanGlaser** [RoboCup-Humanoid-TC/GameController#98]
Hi all,
this year, new sub modes (kick-in, penalty-kick, etc.) were added to the game controller.

First of all, the documentation of the SecondaryStateInfo is misleading. It says 0 for ready, 1 for freeze but apparently the logic is now: 0 and 2 for freeze and 1 for ready.

Second, how are we supposed to handle the 10 second delay after a sub mode? There is no information transmitted by the game controller to inform us that this 10 seconds are running. Is it planned to use the secondary-time variable for that? But then, I was able to get a secondary timer countdown and a sub mode timer countdown at the same time by giving a penalty kick to one team while it was still kicking off. Also related to that is the question of how we are supposed to know which team has throw-in, etc. during that 10 seconds, as the general play mode is "normal". Is it planned to set the kick-off-team variable accordingly?

In general, the states of the game controller are a bit confusing sometimes. Building a memory in our agent to account for all possible actions is rather challenging, as the game controller has an undo functionality and can jump arbitrary in history.

**Comment by sheepsy90** [comment]
Hey Stefan, I agree that the sub state is a little bit of an issue. The problem is that the game controller has a way to complex management of time implemented into it which would need to be addressed first to solve more generic underlying issues.

I don't know the take on that from a commission point of view but architecture wise the gc is a nightmare. 

I implemented the sub states last year as a way to convey nuances in the game state which was modeled not at all intuitive beforehand. 

However I agree with the point that the GC should not assume teams to remember state transitions for counting time themselves as you pointed out that it indeed can jump in time and history.

**Comment by MaikePaetzel** [comment]
The counting time is resolved now by moving the 10 seconds after the execution of a free kick/penalty kick/throw in... into the secondary clock, which means this is now sent to teams via the GameState as usual. For the refactoring of the secondary state info I agree, but I will open a separate ticket for this now.
